# -*- coding: utf-8 -*-
"""Stats_Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9mLHZVZhfonLKMUXBBWFBUC9jjdLYAK
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import ttest_ind
from scipy.stats import f_oneway
from scipy.stats import chi2_contingency
from scipy.stats import pearsonr

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/US_Customer_Insights_Dataset.csv")
print("Dataset Loaded Successfully")

"""## 1. Understand Your Data (10 Marks)"""

df

df.shape

df.head()

df.info()

print(df.duplicated().sum())

df.describe()

df.isnull().sum()

for col in df.columns:
    print(col, ":", df[col].nunique())

numerical_cols = df.select_dtypes(include=np.number).columns
print(numerical_cols)

categorical_cols = df.select_dtypes(include='object').columns
print(categorical_cols)

df.duplicated().sum()

"""## 2. Descriptive Statistics (15 Marks)"""

df[['Age','MonthlySpend',
    'DaysSinceLastInteraction']].describe()

print(df[['Age','MonthlySpend',
          'DaysSinceLastInteraction']].mean())

print(df[['Age',
          'MonthlySpend',
          'DaysSinceLastInteraction']].median())

df[['Age','MonthlySpend',
    'DaysSinceLastInteraction']].median()

df['Gender'].value_counts()

print(df['Gender'].mode())

df['Education'].value_counts()

print(df['Education'].mode())

df['Married'].value_counts()

print(df['Married'].mode())

"""## 3. Data Visualization (15 Marks)"""

plt.figure(figsize=(8,5))
sns.histplot(df['Age'],
             bins=20,kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['MonthlySpend'],
             bins=30,kde=True)
plt.title("Monthly Spend Distribution")
plt.xlabel("Monthly Spend")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(x=df['Age'])
plt.title("Age Boxplot")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(x=df['MonthlySpend'])
plt.title("Monthly Spend Boxplot")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(x=df['MonthlySpend'])
plt.title("Monthly Spend Boxplot")
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(y='Education',data=df)
plt.title("Education Distribution")
plt.show()

plt.figure(figsize=(12,10))
sns.countplot(y='State',
              data=df,
              order=df['State'].value_counts().index)
plt.title("State Distribution")
plt.show()

plt.figure(figsize=(12,10))
sns.countplot(y='State',
              data=df,
              order=df['State'].value_counts().index)
plt.title("State Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.kdeplot(data=df, x='MonthlySpend',hue='Education',fill=True)
plt.title("Monthly Spend by Education")
plt.show()

"""## 4. Bivariate Analysis (15 Marks)"""

corr = df[['Age','NumPets','MonthlySpend','DaysSinceLastInteraction']].corr()
print(corr)

plt.figure(figsize=(8,6))
sns.heatmap(corr,annot=True,cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""## 5. Hypothesis Formulation (10 Marks)"""

cross_tab = pd.crosstab(df['Gender'],df['Married'])
print(cross_tab)

gender_spend = df.groupby('Gender')['MonthlySpend'].mean()
print(gender_spend)

edu_spend = df.groupby('Education')['MonthlySpend'].mean()
print(edu_spend)

state_spend = df.groupby('State')['MonthlySpend'].mean()
print(state_spend)

"""## 6. Hypothesis Testing (20 Marks)"""

male_spend = df[df['Gender']=='Male']['MonthlySpend']

female_spend = df[df['Gender']=='Female']['MonthlySpend']

t_stat,p_val = ttest_ind(male_spend,female_spend)

print("T Statistic:",t_stat)
print("P Value:",p_val)

if p_val < 0.05:
    print("Reject H0")
else:
    print("Fail to Reject H0")

groups = []

for edu in df['Education'].unique():
  groups.append(df[df['Education']==edu]['MonthlySpend'])

f_stat,p_val = f_oneway(*groups)

print("F Statistic:",f_stat)
print("P Value:",p_val)

if p_val < 0.05:
    print("Reject H0")
else:
    print("Fail to Reject H0")

contingency_table = pd.crosstab(df['Married'],df['NumPets'])

chi2,p_val,dof,expected = chi2_contingency(contingency_table)

print("Chi Square:",chi2)
print("P Value:",p_val)

if p_val < 0.05:
    print("Reject H0")
else:
    print("Fail to Reject H0")

corr,p_val = pearsonr(df['Age'],df['DaysSinceLastInteraction'])

print("Correlation:",corr)
print("P Value:",p_val)

if p_val < 0.05:
    print("Reject H0")
else:
    print("Fail to Reject H0")

groups = []

for state in df['State'].unique():
  groups.append(df[df['State']==state]['MonthlySpend'])

f_stat,p_val = f_oneway(*groups)

print("F Statistic:",f_stat)
print("P Value:",p_val)

if p_val < 0.05:
    print("Reject H0")
else:
    print("Fail to Reject H0")

"""## 7. Business Insights & Recommendations (15 Marks)"""

top_states = df.groupby('State')['MonthlySpend'].mean().sort_values(ascending=False)
print(top_states.head(10))

top_edu = df.groupby(
    'Education')[
        'MonthlySpend'].mean().sort_values(ascending=False)
print(top_edu)

df['CustomerSegment'] = pd.qcut(df['MonthlySpend'],q=3,labels=['Low','Medium','High'])
print(df['CustomerSegment'].value_counts())

"""### Business Insights & Recommendations

1. **High-spending customers contribute a significant portion of total revenue**, making them the most valuable customer segment.

   * **Recommendation:** Introduce VIP memberships, exclusive rewards, and premium services to improve retention.

2. **Medium-spending customers represent the greatest growth opportunity** and can potentially be converted into high-value customers.

   * **Recommendation:** Use personalized offers, discounts, and upselling strategies to increase their spending.

3. **Top-performing states generate higher average revenue**, indicating stronger market potential in certain regions.

   * **Recommendation:** Focus marketing efforts and promotional campaigns on these high-performing states.

4. **Education level shows only minor differences in spending behavior**, suggesting it is not a strong predictor of customer value.

   * **Recommendation:** Use education as a secondary segmentation factor rather than a primary targeting criterion.

5. **Premium customers have strong potential for cross-selling and upselling opportunities.**

   * **Recommendation:** Recommend complementary products, premium bundles, and subscription-based services.

6. **Demographic factors such as gender, age, and state have limited influence on spending patterns.**

   * **Recommendation:** Prioritize customer behavior, purchase history, and engagement metrics over demographic attributes.

7. **Behavioral segmentation is the most effective strategy for customer targeting and retention.**

   * **Recommendation:** Build data-driven marketing campaigns based on spending habits, interaction frequency, and customer engagement levels to maximize revenue and customer lifetime value.
"""

plt.figure(figsize=(7,5))
sns.countplot(x='CustomerID', data=df)
plt.xlabel("Customer Segment")
plt.ylabel("Count")
plt.title("Customer Segmentation")
plt.show()

df.to_csv("Customer_Insights_Final.csv",index=False)
print("Dataset Saved Successfully")

"""The analysis examined customer demographics, spending behavior, engagement patterns, and lifestyle factors. Statistical testing revealed that gender, education, age, and state do not significantly influence spending behavior. However, marital status and pet ownership exhibit a significant association. The customer base demonstrates highly skewed spending patterns, indicating the presence of premium-value customers. Businesses should prioritize behavioral segmentation and engagement-based marketing strategies over demographic targeting."""